### ISSUE TITLE
frozen_atom_list in if statement gives nameerror

### ISSUE THREAD

**Issue by Ajaykhanna** [tjz21/Spectroscopy_python_code#1]
https://github.com/tjz21/Spectroscopy_python_code/blob/bb6b80f57a4e4c5bb82ed1a79f754ef3070bce5c/generate_spectra.py#L925
Hi, Tim, the variable "**frozen_atom_list**" is inside the if statement instead of being outside, because of this when you call "**get_hessian_from_terachem**" it gives an error "name '**frozen_atom_list**' is not defined". 

I places it outside the if statement and it worked fine.

**Comment by tjz21** [comment]
Thanks Ajay. I *think* I fixed this but let me know if it still causes issues with the newest version of the code.

**Comment by Ajaykhanna** [comment]
Yes, I saw the changes, it's running smoothly now.
