### ISSUE TITLE
MD example file is missing and traj.dat explanation

### ISSUE THREAD

**Issue by ZKC19940412** [tjz21/Spectroscopy_python_code#2]
Respected developers:
Hi, thank you so much for making this code publicly available and it will greatly benefit us in the community.  I have several questions when running the cumulant example with MD trajectory as input:

1. It seems to say files for MD-based method is missing. Did I run it wrong or is there a way to retrieve required files?

2. For the example trajectory, can you kindly explain what are the meaning of the x and y axes?

3. When running the example, there is a parameter called max_t, can you also elaborate what that is?

Thank you so much for reading this and hope to hear from you soon.

**Comment by tjz21** [comment]
Hi! Thanks for using the code. Please let me know if you have any additional issues. Regarding your question:

1. I assume you mean the example for nonlinear spectroscopy? The input file was indeed wrong, I have committed a new file that should now work. Thanks for pointing this out!
2. In the example file, the x axis is vertical excitation energies for evenly spaced MD snapshots (in units of eV), the y axis is oscillator strengths for those snapshots. Note that for 2DES we invoke the Condon approximation, so we don't actually consider changes in transition dipole moments between snapshots.
3. The parameter max_t is the maximum point in time in fs for which we evaluate the cumulant lineshape function g(t). Together with num_steps, this gives the resolution of t in the time domain. In other words, max_t=300.0 and num_points=300 means g(t) is computed from 0 to 300 fs, in 1 fs intervals.

Hope this helps!
Best wishes,
Tim

**Comment by ZKC19940412** [comment]
1. I am referring to the input file for linear spectroscopy. 
2. Thanks and just a recommendation, it will be nice to include the the descriptions of x and y axis in the .dat file.  
3. Thanks for the explanations. Any rule of thumb between the max_t and the total length of the simulations? Say if we have 100 ps long trajectory, how should we chose max_t?

Again, thank you so much for the clarifications.

**Comment by tjz21** [comment]
Hi Zekun, 

1. Ah ok, this should work fine. So if I move into the directory examples/MD/linear_spectroscopy and type ../../../generate_spectra.py input_file it should run without error. If it produces an error, let me know what that is. 
2. That's a fair enough comment, I will add that
3. So max_t is not related to the total length of your simulation. The total length of the simulation determines the degree to which your correlation function is converged. Max_t determines the resolution of the final spectrum in the frequency domain. If you have very finely resolved spectrum with sharp vibronic peaks, you might need a longer max_t. For realistic systems (a chromophore in solution), max_t=1000.0 fs and num_steps=2000, ie a sampling of g(t) every 0.5 fs is definitely very well converged, and probably significantly overconverged. Computational cost scales with num_steps, so you should not increase it too much if you want the calculation to be fast. But you still want to sample g(t) at least every 1 fs, so num_steps should not be smaller than max_t, to guarantee a 1fs sampling of g(t).

Best wishes,
Tim

**Comment by ZKC19940412** [comment]
Thanks for the response.  The example works fine now. Just have one last question say in my AIMD simulation I did not use OHMIC solvent model, any recommendations on how to modify the solvent response in your code? Again thank you so much for answering all my questions.

**Comment by tjz21** [comment]
Hi Zekun,

The ohmic solvent model is only necessary when you do not construct MD based spectra, but instead calculate a GBOM spectrum. The reason for this is that if you have a finite number of chromophore degrees of freedom in vacuum, your spectrum should in principle just be a sum of delta-functions. This creates numerical issues, so normally we broaden the delta functions by Gaussian functions modeling solvent broadening. However, this is not necessary when using AIMD based correlation functions. In case of the example, the solvent broadening is actually switched off. Setting solvent_reorg, the solvent reorganization energy to 0.000 switches off any contributions from the fictitious solvent model to the absorption lineshape.

**Comment by ZKC19940412** [comment]
Thank you so much everything makes perfect sense now. Thanks for all the clarification.
