### ISSUE TITLE
Issue with Ensemble calculations from MD trajectories

### ISSUE THREAD

**Issue by nickhine** [tjz21/Spectroscopy_python_code#4]
I recently did a pull to a more recent version and it seems some functionality has broken, specifically ensemble calculations based off MD trajectories. Judging by what I could see from git checkouts of older versions, this bug was introduced quite a while ago.

The most easily accessible example is that in examples/MD/linear_spectroscopy which nowadays tries to do a "method: ENSEMBLE" run - it used to do a "method: CUMULANT" run.

If you run this with an older version you get the file photoactive_yellow_protein_MD_cumulant_spectrum.dat which looks like this:
![image](https://user-images.githubusercontent.com/15732143/217760397-d6dd65c7-b792-4163-bda8-251503f75be7.png)

If you run the current version you get this wiggly line in photoactive_yellow_protein_MD_ensemble_spectrum
![image](https://user-images.githubusercontent.com/15732143/217760582-c829aee1-d188-4ef4-9eb3-8b3d65a7781f.png)

If you try the older version with "method: ENSEMBLE" you get a crash:

```
Traceback (most recent call last):
  File "../../../generate_spectra.py", line 1368, in <module>
    compute_MD_absorption(param_set,MDtraj,solvent_mod,False)
  File "../../../generate_spectra.py", line 800, in compute_MD_absorption
    MDtraj.calc_ensemble_response(param_list.max_t,param_list.num_steps)
  File "/storage/nanosim/Spectroscopy_python_code/spec_pkg/cumulant/md_traj.py", line 334, in calc_ensemble_response
    self.ensemble_response=1.0/(np.dot(self.dipole_mom_av,self.dipole_mom_av))*construct_full_ensemble_response(self.fluct,self.dipole_mom, self.mean, max_t,num_steps,self.tau)
  File "/storage/nanosim/Spectroscopy_python_code/spec_pkg/cumulant/md_traj.py", line 36, in construct_full_ensemble_response
    response_func[tcount,1]=ensemble_response_for_given_t(fluctuations,dipole_mom,mean,response_func[tcount,0])*cmath.exp(-1j*mean*tcount*t_step)*np.exp(-abs(tcount*t_step)/decay_const)
TypeError: only length-1 arrays can be converted to Python scalars
```

Any idea what is going wrong there? Do you have a reference result for the photoactive yellow protein MD dataset run in ENSEMBLE mode?

**Comment by nickhine** [comment]
NB: the older version I went back to to check it used to work is; commit b529a76e6ff03bca7d94ef5e3cb918b6038b7c8c

Can confirm the method: CUMULANT run on the current version 387c7a8a5340cbbccfc97b466adb69e628a9e021 still works fine.

**Comment by tjz21** [comment]
Hi Nick, 
Thanks for reaching out. This is indeed broken. Looking into it now! I will let you know once it is fixed. 
Best wishes,
Tim

**Comment by tjz21** [comment]
Hi Nick,

Should be fixed now. Let me know if there are any other issues you find!

Best wishes,
Tim
